### ISSUE TITLE
Faviconの設定

### ISSUE THREAD

**Issue by inuatsu** [ryuugaku-daily/ryuugaku-daily.github.io#6]
MemEのテーマのデフォルトのままなので、何か案があれば更新する。

**Comment by inuatsu** [comment]
アイコン案 1
![icons 002](https://user-images.githubusercontent.com/14820459/87337578-a13e7e80-c57e-11ea-93f1-82506c174c05.png)

**Comment by toshiaki110** [comment]
俺もR的な何かにしたいと思ってた！これにしよう！
